### ISSUE TITLE
[Issue] Multiple collisions on a sprite

### ISSUE THREAD

**Issue by RenaudROHLINGER** [colinvella/phaser-tilemap-plus#1]
Hey !
First of all, awesome work man !

I have some issues in multiples cases like multiple collision at the same time.
Let me explain with an example : 

```
update () {
  // if sprite is colliding on the right and is on the floor then stop animate 
  // ( the sprite got a velocity.x of 200 and a velocity.y of 0)
  if (this.body.contactNormal.x < 0 && this.body.contactNormal.y < 0) {
    // never trigerred since contactNormal.y will always be = 0 because we can actually 
    only check one shape at the same time
  }
}
```

I know it works well with stuff like slopes but when It's a < -1 && < -1 situation there is this issue.
If it is not an issue and I am just doing wrong stuff please help me ^^

**Comment by RenaudROHLINGER** [comment]
Furthermore, could it be possible to update the body physics properties like sprite.body.blocked and sprite.body.touching based on your extension ?

**Comment by colinvella** [comment]
Hi,

I think the solution would be for the plugin to set the blocked and touching properties as you suggested. As a temporary measure, did you try to set them manually based on contactNormal?

The issue can also be noticed in the demo in fact. I'll find a work around as soon as I can and will update the package.

**Comment by RenaudROHLINGER** [comment]
I added a method to update the flags in your Physics.js file (called in collideWidth)

```
    updateFlags (sprite, contactNormal) {
        const body = sprite.body;

        body.touching.up    = body.touching.up    || contactNormal.y > 0;
        body.touching.down  = body.touching.down  || contactNormal.y < 0;
        body.touching.left  = body.touching.left  || contactNormal.x > 0;
        body.touching.right = body.touching.right || contactNormal.x < 0;
        body.touching.none  = !body.touching.up && !body.touching.down && !body.touching.left && !body.touching.right;

        // Set the blocked values
        body.blocked.up    = body.blocked.up    || contactNormal.x === 0 && contactNormal.y > 0;
        body.blocked.down  = body.blocked.down  || contactNormal.x === 0 && contactNormal.y < 0;
        body.blocked.left  = body.blocked.left  || contactNormal.y === 0 && contactNormal.x > 0;
        body.blocked.right = body.blocked.right || contactNormal.y === 0 && contactNormal.x < 0;
    }
```

It works fine but the main problem is still that the contactNormal.y === 0 when contactNormal.x === - 1 || 1

As Leonardo DiCaprio would say in the movie Inception : 
"We need to go deeper"

**Comment by colinvella** [comment]
One of the challenges with dealing with this issue is that the contact normal and penetration vector are accumulated so that if you're walking into a wall, rather than getting these two vector quantities per each  surface (floor and wall), you get them combined. That is, for the contact normal, you get a diagonal vector pointing away from both the floor and wall (think of a vector jutting from the corner when floor meets wall and pointing towards your sprite).

I think I'll need to alter the contact resolution code to yield contact normals and penetration vectors for each surface that the sprite is in contact with. For the sake of back compatibility, the accumulated quantities will still be retained. In this manner, it will be possible to check if the sprite is touching a wall that is impeding walking and disable the animation accordingly.

**Comment by colinvella** [comment]
The physics module now sets the blocking flags accordingly. Touching is not set because this is for sprite to sprite collisions only. Besides an overall contact normal,an array of all contact normals from all surface collisions is attached to the body. This allows for vertical or near vertical wall testing so that walk animations may be disabled where applicable.
